branches: master

pipeline:
  analysis:
    image: alpine
    commands: |
      apk add --no-cache build-base cppcheck clang-extra-tools \
          imlib2-dev xorgproto \
          libxft-dev libexif-dev giflib-dev libwebp-dev >/dev/null
      make config.h version.h
      ./etc/woodpecker/analysis.sh
